# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-20 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_closed',
            field=models.DateField(default=None, null=True),
        ),
    ]
