# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_issue_date_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_closed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
