# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-29 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='foo',
        ),
    ]
