# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entered_by', models.CharField(max_length=40)),
                ('subj', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=512)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
