# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200208_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='desc',
            field=models.TextField(),
        ),
    ]
