# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-13 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200208_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
