# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entered_by', models.CharField(max_length=40)),
                ('feature', models.CharField(max_length=80)),
                ('desc', models.TextField()),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
