# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-16 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='current_bid',
            new_name='bid',
        ),
    ]
