# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_remove_feature_entered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='entered_by',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
    ]
