# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-20 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0003_auto_20200218_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='date_completed',
            field=models.DateField(default=None, null=True),
        ),
    ]
