# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0004_feature_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='date_completed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
