# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-26 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0005_auto_20200220_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='date_accept_or_deny',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
