# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0006_feature_date_accept_or_deny'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='date_paid',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
