# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0008_feature_entered_by_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='entered_by_email',
            field=models.EmailField(max_length=80),
        ),
    ]
